#+TITLE: Tweet.Tone (work in progress)

* Table of Contents
:PROPERTIES:
:TOC:      this
:END:
-  [[#description][Description]]
-  [[#dependencies][Dependencies]]
-  [[#installation][Installation]]
-  [[#authentication][Authentication]]
-  [[#usage][Usage]]
-  [[#credits-and-thanks][Credits and Thanks]]
-  [[#authors][Authors]]

* Description
Given a link to a specific tweet, *Tweet.Tone* will fetch the tweet
and analyze the emotional tones in its contentusing IBM Watson's [[https://cloud.ibm.com/docs/services/tone-analyzer?topic=tone-analyzer-about#about][Tone
Analyzer]]. It will then display the most dominant tones as colored dots
next to the Tweet as well as generating tones for any comments made
directly in response to it. The tones for the comments will be
generated in a rectangular array of dots colored by tones under the
searched tweet.

Additionally the user may click on any of the comment dots which will show its
content along with its most dominant tone breakdown.

* Dependencies
|------------+---------|
| Dependency | Version |
|------------+---------|
| Python     |     3.6 |
| Bash       |       4 |
|------------+---------|

* Installation
1) Clone this repository
2) Install the Python requirements (preferably in a virtual environment of your choice)
   #+begin_src bash
     pip install -r requirements.txt
   #+end_src

* Authentication
1) To use *Tweet.Tone* it is necessary to sign up for an [[https://cloud.ibm.com/registration?target=%2Fcatalog%2Fservices%2Ftone-analyzer][IBM Cloud Account]] and then [[https://cloud.ibm.com/catalog/services/tone-analyzer][create an instance of the IBM Watson Tone Analyzer]].
2) Create a file name ~.env~ in the root directory of the repository
3) Add the following lines to the bottom of ~.env~ replacing the angle brackets and their contents with your corresponding credentials.
   #+begin_src bash
     export TONE_KEY="<api-token-from-IBM-cloud-account-tone-analyzer>"
     export TONE_URL="<api-url-from-IBM-cloud-account-tone-analyzer>"
     export SECRET_KEY="<your-choice-of-secret-key-for-flask-app>"
   #+end_src
4) Make the ~.env~ executable.
   #+begin_src bash
     chmod u+x .env
   #+end_src

* Usage
1) ~cd~ to the root directory of the repo.
2) Source ~.env~ to apply the environment variables.
   #+begin_src bash
     . .env
   #+end_src
3) Create the app (make sure your virtual enviornment is activated if you are using one)
   #+begin_src bash
     flask run
   #+end_src
4) As deployment has not been completed, visit app locally on your machine at http://localhost:5000.

* Credits and Thanks
- [[https://www.ibm.com/watson][IBM Watson]]
- [[https://coreyms.com/][Corey Schafer]]
- [[https://www.udemy.com/user/coltsteele/][Colt Steele]]
- [[https://www.w3schools.com/][w3schools]]
- [[https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer][Ritwick Dey]]

* Authors
- [[https://github.com/kylebell3][Kyle Bell]]
- [[https://github.com/RyanIn3D/][Ryan Davis]]
- [[https://github.com/jeremytsang1][Jeremy Tsang]]

# Local Variables:
# before-save-hook: org-make-toc
# End:



